apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.app_name }}-service
  labels:
    app: {{ .Values.app.app_name }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.containerPort }}
  selector:
    app: {{ .Values.app.app_name }}